project_id = "vbnazlnwudhewjgftxce"

[functions.confirm-order-received-v2]
verify_jwt = false
  
[functions.confirm-order-received]
verify_jwt = false

[functions.create-order]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.send-order-emails]
verify_jwt = false

[functions.send-abandoned-cart-email]
verify_jwt = false

[functions.send-low-stock-email]
verify_jwt = true

[functions.send-order-status-email]
verify_jwt = true

[functions.calculate-shipping]
verify_jwt = false

[functions.get-order-confirmation]
verify_jwt = false

[functions.delete-user]
verify_jwt = true

[functions.send-review-request-email]
verify_jwt = false

[functions.create-mercadopago-checkout]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false

[functions.test-order-email]
verify_jwt = false

[functions.test-resend-email]
verify_jwt = false

[functions.admin-trigger-emails]
verify_jwt = false

[functions.create-user]
verify_jwt = true

[functions.update-user]
verify_jwt = true

[functions.get-user-email]
verify_jwt = true

[functions.magic-login]
verify_jwt = false

[functions.verify-magic]
verify_jwt = false

[functions.confirm-order-magic]
verify_jwt = false

[functions.get-order-items-magic]
verify_jwt = false
