project_id = "vbnazlnwudhewjgftxce"

[functions.create-user]
verify_jwt = true

[functions.create-order]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
